### ISSUE TITLE
Assertion Error Line 330

### ISSUE THREAD

**Issue by willettjf** [NishantTharani/LogSeqToObsidian#10]
Can anyone help diagnose this error?

Traceback (most recent call last):
  File "~/Desktop/convert_notes.py", line 330, in <module>
    assert os.path.exists(old_base) and os.path.isdir(old_base)
AssertionError

**Comment by NishantTharani** [comment]
HI @willettjf - that error message indicates that whatever you supplied as the path to your logseq graph either does not exist, or is not a valid directory. Were you able to solve the issue? Is it possible that you made a mistake when supplying the path as an argument?

PS I replaced this opaque message with a more informative error message, thanks for being the first person to bring this up :)

**Comment by willettjf** [comment]
Thanks! I did have an error in the directory. Tried again and ran into one more problem.

Line 346: os.makedirs(new_base, exist_ok=False)

Changed to True, and it worked.
