### ISSUE TITLE
Seeking Assistance to Improve the Script and Resolve Markdown Issues

### ISSUE THREAD

**Issue by kl2111** [NishantTharani/LogSeqToObsidian#4]
Hi, there

First of all, I want to express my gratitude for your script. I am delighted to inform you that the script has been successfully executed and has performed well in certain aspects. 

0. The script has run successfully and has shown promising results.

1. I have noticed that the script has made some improvements in handling properties. The previous `::` has been successfully converted to a colon (`:`). For example, `Public:: true` is now transformed into `Public: true`. This improvement aligns the property format with the expected standard.

2. However, there are still some issues that need to be addressed. The hyphen symbol (`-`) in unordered lists is still present before the highest-level item, and we would like to remove it.

3. Additionally, a forward slash (`/`) has been added before the quotation symbol (`>`) which causes the quotation symbol to be incorrectly recognized.

4. Furthermore, there is still a significant amount of indentation present, and we would like to remove it to align the content to the left.

I would appreciate it if you could provide suggestions to help optimize this script and achieve the desired outcome. Thank you for your assistance.

Best regards,
KL

![](http://ouyoung.oss-cn-zhangjiakou.aliyuncs.com/upic/k8aft1.jpg)

**Comment by NishantTharani** [comment]
Hi,

My apologies for the very slow reply. I am glad you are finding the tool useful. I hope I am not too late to help you, but in any case I appreciate the feedback as it may be useful to others in the future!

2 and 4: I tried to fix this. If you add the flag `--unindent_once`, it should unindent every line once. This means that on lines at the highest level, the bullet point will be removed. And lines indented N times will now be indented N-1 times.

3: This should be fixed, the `>` and `<` symbols will no longer be escaped with a `\` if they are at the start of a line, or inside a codeblock.

Let me know if this helps!

**Comment by ReessKennedy** [comment]
+1 ... wanting to thank you to @NishantTharani  ... does this mean you fully switched from Logseq to Obsidian or you still use both? ... laughed at the line you wrote in the docs about your penchant for switching to different notes apps. This resonated.

**Comment by NishantTharani** [comment]
@ReessKennedy I'm using Obsidian fully now. Mainly I like having a native folders + files interface (as well as backlinks and everything) because sometimes it just feels natural to me. It feels easier to manage a lot of notes across different areas of my life, if there are some folders :)

But as you say, I wouldn't bet against me switching apps again one day :D

**Comment by NishantTharani** [comment]
@KL2101 Forgot to tag you by username in my reply to you - do you still need help with this issue? If not I'll close it after some time.
